language: ruby
rvm:
  - 2.2

branches:
  only:
    - master
    - nginx-1.9.x

env:
  - NGX_VERSION_ENV=0.8.54
  - NGX_VERSION_ENV=0.8.55
  - NGX_VERSION_ENV=1.0.11
  - NGX_VERSION_ENV=1.4.2
  - NGX_VERSION_ENV=1.6.2
  - NGX_VERSION_ENV=1.7.8
  - NGX_VERSION_ENV=1.7.9
  - NGX_VERSION_ENV=1.7.10
  - NGX_VERSION_ENV=1.7.11
  - NGX_VERSION_ENV=1.7.12
  - NGX_VERSION_ENV=1.8.0
  - NGX_VERSION_ENV=1.9.0
  - NGX_VERSION_ENV=1.9.1
  - NGX_VERSION_ENV=1.9.2
  - NGX_VERSION_ENV=1.9.4

before_install:
  - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq gcc-4.8 g++-4.8 apache2-utils
  - travis_retry sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
  - bundle install --jobs=3 --retry=3
  - travis_retry rake nginx:compile

script: rake test

notifications:
  slack:
    secure: urkEHEdmCiPHvQFJD6+6G+oih+qq8WD+qLoiCZnEI9p54SGfrt8c0Q4EFcn9470Hye7UOTF4sdPYwtdFTqcjFKvCNhx2hYVbmS4gI6b+LTPGvGyXvazWi7dptFL33kuAB05I/gkqKrJH2XXLRIIXEaB/nsRSDDkxPdKtjO3ykzQ=
